# Generated by Django 4.2.2 on 2023-06-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='problem',
            name='amount',
            field=models.BigIntegerField(null=True, verbose_name='Сумма'),
        ),
    ]
