# Generated by Django 4.2.2 on 2023-06-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_problem_active_problem_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='active',
            new_name='is_active',
        ),
    ]
